# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tmdb_swipebox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'XCoordinator', '~> 2.0'
  pod 'Then'
  pod 'TinyConstraints'
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.0'
  # Pods for tmdb_swipebox

end
